# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


student_requests = [{:uin => '126003824', :name => 'Mo Li', 
                     :major => 'CEEN', :classification => 'G7', :minor => 'CECN', :email => 'king_lm@tamu.edu', :phone => '9797797697', 
                     :expected_graduation => '2019 Fall', :request_semester => '2019 Fall',
                     :course_id => '026', :section_id => '101', :notes => 'Requirement for graduation.',:priority => 'Very High' , :state => 'Active'},
                     {:uin => '126003824', :name => 'Mo Li', 
                      :major => 'CEEN', :classification => 'G7', :minor => 'CECN', :email => 'king_lm@tamu.edu', :phone => '9797769279', 
                      :expected_graduation => '2019 Fall', :request_semester => '2019 Fall',
                      :course_id => '026', :section_id => '101', :notes => 'I need this course as my summer intern will deal with this.',:priority => 'Very High' , :state => 'Active'},
                      {:uin => '126003824', :name => 'Mo Li', 
                      :major => 'CEEN', :classification => 'G7', :minor => 'CECN', :email => 'king_lm@tamu.edu', :phone => '9793477979', 
                      :expected_graduation => '2019 Fall', :request_semester => '2019 Fall',
                      :course_id => '027', :section_id => '101', :notes => 'My research advisor has recommended this course.' ,:priority => 'Very High', :state => 'Active'},
                      
                      {:uin => '222111333', :name => 'Jiechen Zhong', 
                      :major => 'CEEN', :classification => 'G8', :minor => 'MATH', :email => 'chen0209app@tamu.edu', :phone => '9797797900', 
                      :expected_graduation => '2019 Fall', :request_semester => '2019 Fall',
                      :course_id => '026', :section_id => '101', :notes => 'I am interested in CS026 as it is my field of research.' ,:priority => 'Very High', :state => 'Active'},
                      {:uin => '222111333', :name => 'Jiechen Zhong', 
                      :major => 'CEEN', :classification => 'G8', :minor => 'PHYS', :email => 'chen0209app@tamu.edu', :phone => '9797797900', 
                      :expected_graduation => '2019 Fall', :request_semester => '2019 Fall',
                      :course_id => '028', :section_id => '101', :notes => 'I need this subject to graduate.',:priority => 'Very High' , :state => 'Active'},
                  ]


majors = [  
            {:major_id => 'None'},
            {:major_id => 'AALO'},
            {:major_id => 'ACCT'},
            {:major_id => 'ADDT'},
            {:major_id => 'AEGD'},
            {:major_id => 'AERO'},
            {:major_id => 'AERS'},
            {:major_id => 'AFST'},
            {:major_id => 'AGCJ'},
            {:major_id => 'AGEC'},
            {:major_id => 'AGLS'},
            {:major_id => 'AGSC'},
            {:major_id => 'AGSM'},
            {:major_id => 'ALEC'},
            {:major_id => 'ANES'},
            {:major_id => 'ALED'},
            {:major_id => 'ANSC'},
            {:major_id => 'ANTH'},
            {:major_id => 'ARAB'},
            {:major_id => 'ARCH'},
            {:major_id => 'AREN'},
            {:major_id => 'ARTS'},
            {:major_id => 'ASCC'},
            {:major_id => 'ASIA'},
            {:major_id => 'ASTR'},
            {:major_id => 'ATMO'},
            {:major_id => 'ATTR'},
            {:major_id => 'BAEN'},
            {:major_id => 'BEFB'},
            {:major_id => 'BESC'},
            {:major_id => 'BICH'},
            {:major_id => 'BIED'},
            {:major_id => 'BIMS'},
            {:major_id => 'BIOL'},
            {:major_id => 'BUAD'},
            {:major_id => 'BMEN'},
            {:major_id => 'BUSH'},
            {:major_id => 'BOTN'},
            {:major_id => 'BUSN'},
            {:major_id => 'CAEN'},
            {:major_id => 'CARC'},
            {:major_id => 'CEHD'},
            {:major_id => 'CHEM'},
            {:major_id => 'CHEN'},
            {:major_id => 'CHIN'},
            {:major_id => 'CLAS'},
            {:major_id => 'CLEN'},
            {:major_id => 'CLSL'}, 
            {:major_id => 'COMM'},
            {:major_id => 'COSC'},
            {:major_id => 'CPSY'},
            {:major_id => 'CSCE'}, 
            {:major_id => 'CVEN'},
            {:major_id => 'CYBR'},
            {:major_id => 'DASC'},
            {:major_id => 'DDDS'},
            {:major_id => 'DHUM'},
            {:major_id => 'DPHS'},
            {:major_id => 'DCED'},
            {:major_id => 'DDHS'},
            {:major_id => 'DIVE'},
            {:major_id => 'ECEN'},
            {:major_id => 'ECHE'},
            {:major_id => 'ECMT'},
            {:major_id => 'ECON'},
            {:major_id => 'EDAD'},
            {:major_id => 'EDCI'},
            {:major_id => 'EDHP'},
            {:major_id => 'EDTC'},
            {:major_id => 'EEBL'},
            {:major_id => 'EHRD'},
            {:major_id => 'EMED'},
            {:major_id => 'ENDO'},
            {:major_id => 'ENDG'},
            {:major_id => 'ENDS'},
            {:major_id => 'ENGL'},
            {:major_id => 'ENGR'},
            {:major_id => 'ENST'},
            {:major_id => 'ENTC'},
            {:major_id => 'ENTO'},
            {:major_id => 'EPFB'},
            {:major_id => 'EPSY'},
            {:major_id => 'ESET'},
            {:major_id => 'ESSM'},
            {:major_id => 'EURO'},
            {:major_id => 'EVEN'},
            {:major_id => 'FILM'},
            {:major_id => 'FINC'},
            {:major_id => 'FORS'},
            {:major_id => 'FIVS'},
            {:major_id => 'FREN'},
            {:major_id => 'FRSC'},
            {:major_id => 'GALV'},
            {:major_id => 'GENE'},
            {:major_id => 'GEOG'},
            {:major_id => 'GEOL'},
            {:major_id => 'GEOP'},
            {:major_id => 'GEOS'},
            {:major_id => 'GERM'},
            {:major_id => 'HCPI'},
            {:major_id => 'HBRW'},
            {:major_id => 'HEFB'},
            {:major_id => 'HHUM'},
            {:major_id => 'HISP'},
            {:major_id => 'HIST'},
            {:major_id => 'HLTH'},
            {:major_id => 'HORT'},
            {:major_id => 'HPCH'},
            {:major_id => 'HUMA'},
            {:major_id => 'IBST'},
            {:major_id => 'IBUS'},
            {:major_id => 'ICPE'},
            {:major_id => 'IDIS'},
            {:major_id => 'IMED'},
            {:major_id => 'INTA'},
            {:major_id => 'INST'},
            {:major_id => 'INTS'},
            {:major_id => 'ISEN'},
            {:major_id => 'ISTM'},
            {:major_id => 'ITAL'},
            {:major_id => 'ITDE'},
            {:major_id => 'JAPN'},
            {:major_id => 'JOUR'},
            {:major_id => 'KINE'},
            {:major_id => 'KNFB'},
            {:major_id => 'LAND'},
            {:major_id => 'LAW'},
            {:major_id => 'LBAR'},
            {:major_id => 'LDEV'},
            {:major_id => 'LING'},
            {:major_id => 'LMAS'},
            {:major_id => 'MARA'},
            {:major_id => 'MARB'},
            {:major_id => 'MARE'}, 
            {:major_id => 'MARR'},
            {:major_id => 'MARS'},
            {:major_id => 'MART'},
            {:major_id => 'MASC'},
            {:major_id => 'MASE'},
            {:major_id => 'MAST'},
            {:major_id => 'MATH'},
            {:major_id => 'MCMD'},
            {:major_id => 'MEEN'},
            {:major_id => 'MEFB'},
            {:major_id => 'MEID'},
            {:major_id => 'MEMA'},
            {:major_id => 'MEPS'},
            {:major_id => 'MFCM'},
            {:major_id => 'METR'},
            {:major_id => 'MGMT'},
            {:major_id => 'MHUM'},
            {:major_id => 'MICR'},
            {:major_id => 'MKTG'},
            {:major_id => 'MLSC'},
            {:major_id => 'MMET'},
            {:major_id => 'MODL'},
            {:major_id => 'MPAT'},
            {:major_id => 'MPED'},
            {:major_id => 'MPHY'},
            {:major_id => 'MPIM'},
            {:major_id => 'MPSY'},
            {:major_id => 'MRAD'},
            {:major_id => 'MSCI'},
            {:major_id => 'MSEN'},
            {:major_id => 'NEXT'},
            {:major_id => 'MUSC'},
            {:major_id => 'MUST'},
            {:major_id => 'MXET'},
            {:major_id => 'NAUT'},
            {:major_id => 'NFSC'},
            {:major_id => 'NRSC'},
            {:major_id => 'NUEN'},
            {:major_id => 'NURS'},
            {:major_id => 'NVSC'},
            {:major_id => 'OBGY'},
            {:major_id => 'OBIO'},
            {:major_id => 'OCEN'},
            {:major_id => 'OCNG'},
            {:major_id => 'OCRE'},
            {:major_id => 'OMFP'},
            {:major_id => 'OMFR'},
            {:major_id => 'OMFS'},
            {:major_id => 'ORTH'},
            {:major_id => 'PEDD'},
            {:major_id => 'PERF'},
            {:major_id => 'PERI'},
            {:major_id => 'PETE'},
            {:major_id => 'PHAR'},
            {:major_id => 'PHEB'},
            {:major_id => 'PHEO'},
            {:major_id => 'PHIL'},
            {:major_id => 'PHPM'},
            {:major_id => 'PHLT'},
            {:major_id => 'PHYS'},
            {:major_id => 'PLAN'},
            {:major_id => 'PLPA'},
            {:major_id => 'POLS'},
            {:major_id => 'PORT'},
            {:major_id => 'POSC'},
            {:major_id => 'PROS'},
            {:major_id => 'PSAA'},
            {:major_id => 'PSYC'},
            {:major_id => 'RDNG'},
            {:major_id => 'RELS'},
            {:major_id => 'RENR'},
            {:major_id => 'RLEM'},
            {:major_id => 'RPTS'},
            {:major_id => 'RUSS'},
            {:major_id => 'SCEN'},
            {:major_id => 'SCMT'},
            {:major_id => 'SCSC'},
            {:major_id => 'SEFB'},
            {:major_id => 'SENG'},
            {:major_id => 'SOCI'},
            {:major_id => 'SOPH'},
            {:major_id => 'SOMS'},
            {:major_id => 'SPAN'},
            {:major_id => 'SPED'},
            {:major_id => 'SPMT'},
            {:major_id => 'SPSY'},
            {:major_id => 'SPSC'},
            {:major_id => 'STAT'},
            {:major_id => 'STLC'},
            {:major_id => 'TCMG'},
            {:major_id => 'SURG'},
            {:major_id => 'SYEN'},
            {:major_id => 'TAMU'},
            {:major_id => 'TCMT'},
            {:major_id => 'TEED'},
            {:major_id => 'URSC'},
            {:major_id => 'TEFB'},
            {:major_id => 'THAR'},
            {:major_id => 'UGST'},
            {:major_id => 'URPN'},
            {:major_id => 'VIBS'},
            {:major_id => 'VIZA'},
            {:major_id => 'VIST'},
            {:major_id => 'VLCS'},
            {:major_id => 'VMID'},
            {:major_id => 'VPAR'},
            {:major_id => 'VPAT'},
            {:major_id => 'VSCS'},
            {:major_id => 'VTMI'},
            {:major_id => 'VTPB'},
            {:major_id => 'VTPP'},
            {:major_id => 'WFSC'},
            {:major_id => 'WGST'},
            {:major_id => 'WMHS'},
            {:major_id => 'ZOOL'},
            {:major_id => 'Others'}               
            ]
            
admins = [{:uin => '123456789', :name => 'admin', :password => 'tamu2017', :email => '123456789@tamu.edu'},
          {:uin => '987654321', :name => 'admin2', :password => 'tamu2017', :email => '123456780@tamu.edu'}]


limits = [{:classification => 'G7', "Very High".to_sym => '99', :High => '99', :Normal => '99', :Low => '99', "Very Low".to_sym => '99'}, 
          {:classification => 'U1', "Very High".to_sym => '99', :High => '99', :Normal => '99', :Low => '99', "Very Low".to_sym => '99'},
          {:classification => 'U2', "Very High".to_sym => '99', :High => '99', :Normal => '99', :Low => '99', "Very Low".to_sym => '99'},
          {:classification => 'U3', "Very High".to_sym => '99', :High => '99', :Normal => '99', :Low => '99', "Very Low".to_sym => '99'},
          {:classification => 'U4', "Very High".to_sym => '99', :High => '99', :Normal => '99', :Low => '99', "Very Low".to_sym => '99'},
          {:classification => 'U5', "Very High".to_sym => '99', :High => '99', :Normal => '99', :Low => '99', "Very Low".to_sym => '99'},
          {:classification => 'G8', "Very High".to_sym => '99', :High => '99', :Normal => '99', :Low => '99', "Very Low".to_sym => '99'}]

students = [{uin: "126003824", password: "123123", major: "Computer Engineering - CEEN", classification: "G7-Graduate, Master's Level", name: "Mo Li", email: "king_lm@tamu.edu"},
            {uin: "123123123", password: "321", major: "Computer Engineering - CEEN", classification: "G8-Graduate", name: "Mian Qin", email: "celery1124@tamu.edu"},
            {uin: "222111333", password: "zxc", major: "Computer Engineering - CEEN", classification: "G7-Graduate, Master's Level", name: "Jiechen Zhong", email: "chen0209app@tamu.edu"},
            ]



limits.each do |limit|
  Limit.create!(limit)
end

students.each do |student|
   Student.create!(student) 
end

student_requests.each do |record|
  StudentRequest.create!(record)
end

majors.each do |record|
  Major.create!(record)
end

admins.each do |record|
  Admin.create!(record)
end
